name: "Fresh-bot"
author: "c-hive"
description: ""
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  GITHUB_TOKEN:
    description: "Personal access token with full control of private repositories scope enabled"
    required: true
  FOR_REAL:
    description: "Internal use, kind of a hack, I'm too lazy to figure out how to do this properly right now"
    required: false
    default: "1"
